steps:
  # build docker image for target sub-pacakge
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp yarn.lock packages/$_TARGET_PACKAGE
        cd packages/$_TARGET_PACKAGE
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$_IMAGE_NAME:${BRANCH_NAME}_${SHORT_SHA}

  # Deploy container image to dev Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_CLOUD_RUN_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${BRANCH_NAME}_${SHORT_SHA}'
      - '--region'
      - 'asia-east1'

timeout: 1200s

substitutions:
  _TARGET_PACKAGE: '' # default value
  _IMAGE_NAME: '' # default value
  _CLOUD_RUN_SERVICE_NAME: '' # default value
